import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const root = path.resolve(import.meta.dirname, "..");
const dynamicDir = path.join(root, "nemc-form-script", "behavior_pack", "form_script", "server", "executor", "language", "builtins", "dynamic");
const output = path.join(root, "src", "catalog", "generated.ts");
const names = new Set();
for (const entry of await readdir(dynamicDir, { withFileTypes: true })) {
  if (!entry.isFile() || !entry.name.endsWith(".py")) continue;
  const text = await readFile(path.join(dynamicDir, entry.name), "utf8");
  for (const match of text.matchAll(/funcs\[\s*["']([^"']+)["']\s*\]/g)) names.add(match[1]);
}
const values = [...names].sort();
const generated = `// Generated by scripts/generate-catalog.mjs; do not edit.\nexport const ACTUAL_DYNAMIC_API_NAMES = Object.freeze(${JSON.stringify(values, null, 2)} as const);\n`;
if (process.argv.includes("--check")) {
  const current = await readFile(output, "utf8").catch(() => "");
  if (current !== generated) {
    console.error("Runtime catalog drift detected; run node scripts/generate-catalog.mjs");
    process.exitCode = 1;
  }
} else {
  await writeFile(output, generated, "utf8");
  console.log(`Generated ${path.relative(root, output)} with ${values.length} dynamic APIs.`);
}
